name: Simulated Jenkins Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (Assuming Gradle build is using Java)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'openjdk'

      # Step 3: Cache Gradle dependencies to speed up builds
      #- name: Cache Gradle dependencies
       # uses: actions/cache@v2
        #with:
          #path: ~/.gradle/caches
         # key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          #restore-keys: |
           # ${{ runner.os }}-gradle-

      # Step 4: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew assemble

      # Step 5: Run tests with Gradle
      - name: Run tests with Gradle
        run: ./gradlew test
